#spring application name
spring.application.name=backend

#port no
server.port=8080

#mysql database properties
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d69hk28gjchc73diqq3g-a.singapore-postgres.render.com:5432/my_employee_management_system_db?sslmode=require
spring.datasource.username=my_employee_management_system_db_user
spring.datasource.password=Szy4qKbwMsPO01xk5qPKQcvkiA2KUQM4

#Hibernate and Jpa Properties
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
